/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DriverLoginRouteImport } from './routes/driver-login'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TravelerLoginRouteImport } from './routes/traveler-login'
import { Route as TravelerPortalRouteImport } from './routes/traveler-portal'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppIndiaAdmissionsRouteImport } from './routes/_app.india-admissions'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppPartnersRouteImport } from './routes/_app.partners'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppTravelRouteImport } from './routes/_app.travel'
import { Route as AppTravelDestinationsRouteImport } from './routes/_app.travel-destinations'
import { Route as AppTravelServicesRouteImport } from './routes/_app.travel-services'
import { Route as AppUniversitiesRouteImport } from './routes/_app.universities'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app.students.$studentId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver-login',
  path: '/driver-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerLoginRoute = TravelerLoginRouteImport.update({
  id: '/traveler-login',
  path: '/traveler-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerPortalRoute = TravelerPortalRouteImport.update({
  id: '/traveler-portal',
  path: '/traveler-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppIndiaAdmissionsRoute = AppIndiaAdmissionsRouteImport.update({
  id: '/india-admissions',
  path: '/india-admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTravelRoute = AppTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AppRoute,
} as any)
const AppTravelDestinationsRoute = AppTravelDestinationsRouteImport.update({
  id: '/travel-destinations',
  path: '/travel-destinations',
  getParentRoute: () => AppRoute,
} as any)
const AppTravelServicesRoute = AppTravelServicesRouteImport.update({
  id: '/travel-services',
  path: '/travel-services',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversitiesRoute = AppUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/driver-login': typeof DriverLoginRoute
  '/driver-portal': typeof DriverPortalRoute
  '/login': typeof LoginRoute
  '/traveler-login': typeof TravelerLoginRoute
  '/traveler-portal': typeof TravelerPortalRoute
  '/applications': typeof AppApplicationsRoute
  '/approvals': typeof AppApprovalsRoute
  '/finance': typeof AppFinanceRoute
  '/hr': typeof AppHrRoute
  '/india-admissions': typeof AppIndiaAdmissionsRoute
  '/leads': typeof AppLeadsRoute
  '/partners': typeof AppPartnersRoute
  '/portal': typeof AppPortalRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/travel': typeof AppTravelRoute
  '/travel-destinations': typeof AppTravelDestinationsRoute
  '/travel-services': typeof AppTravelServicesRoute
  '/universities': typeof AppUniversitiesRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/driver-login': typeof DriverLoginRoute
  '/driver-portal': typeof DriverPortalRoute
  '/login': typeof LoginRoute
  '/traveler-login': typeof TravelerLoginRoute
  '/traveler-portal': typeof TravelerPortalRoute
  '/applications': typeof AppApplicationsRoute
  '/approvals': typeof AppApprovalsRoute
  '/finance': typeof AppFinanceRoute
  '/hr': typeof AppHrRoute
  '/india-admissions': typeof AppIndiaAdmissionsRoute
  '/leads': typeof AppLeadsRoute
  '/partners': typeof AppPartnersRoute
  '/portal': typeof AppPortalRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/travel': typeof AppTravelRoute
  '/travel-destinations': typeof AppTravelDestinationsRoute
  '/travel-services': typeof AppTravelServicesRoute
  '/universities': typeof AppUniversitiesRoute
  '/': typeof AppIndexRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/driver-login': typeof DriverLoginRoute
  '/driver-portal': typeof DriverPortalRoute
  '/login': typeof LoginRoute
  '/traveler-login': typeof TravelerLoginRoute
  '/traveler-portal': typeof TravelerPortalRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/india-admissions': typeof AppIndiaAdmissionsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/travel': typeof AppTravelRoute
  '/_app/travel-destinations': typeof AppTravelDestinationsRoute
  '/_app/travel-services': typeof AppTravelServicesRoute
  '/_app/universities': typeof AppUniversitiesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/_app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver-login'
    | '/driver-portal'
    | '/login'
    | '/traveler-login'
    | '/traveler-portal'
    | '/applications'
    | '/approvals'
    | '/finance'
    | '/hr'
    | '/india-admissions'
    | '/leads'
    | '/partners'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/students'
    | '/travel'
    | '/travel-destinations'
    | '/travel-services'
    | '/universities'
    | '/students/$studentId'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/driver-login'
    | '/driver-portal'
    | '/login'
    | '/traveler-login'
    | '/traveler-portal'
    | '/applications'
    | '/approvals'
    | '/finance'
    | '/hr'
    | '/india-admissions'
    | '/leads'
    | '/partners'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/travel'
    | '/travel-destinations'
    | '/travel-services'
    | '/universities'
    | '/'
    | '/students/$studentId'
    | '/students'
  id:
    | '__root__'
    | '/_app'
    | '/driver-login'
    | '/driver-portal'
    | '/login'
    | '/traveler-login'
    | '/traveler-portal'
    | '/_app/applications'
    | '/_app/approvals'
    | '/_app/finance'
    | '/_app/hr'
    | '/_app/india-admissions'
    | '/_app/leads'
    | '/_app/partners'
    | '/_app/portal'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/travel'
    | '/_app/travel-destinations'
    | '/_app/travel-services'
    | '/_app/universities'
    | '/_app/'
    | '/_app/students/$studentId'
    | '/_app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DriverLoginRoute: typeof DriverLoginRoute
  DriverPortalRoute: typeof DriverPortalRoute
  LoginRoute: typeof LoginRoute
  TravelerLoginRoute: typeof TravelerLoginRoute
  TravelerPortalRoute: typeof TravelerPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-login': {
      id: '/driver-login'
      path: '/driver-login'
      fullPath: '/driver-login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler-login': {
      id: '/traveler-login'
      path: '/traveler-login'
      fullPath: '/traveler-login'
      preLoaderRoute: typeof TravelerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler-portal': {
      id: '/traveler-portal'
      path: '/traveler-portal'
      fullPath: '/traveler-portal'
      preLoaderRoute: typeof TravelerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/india-admissions': {
      id: '/_app/india-admissions'
      path: '/india-admissions'
      fullPath: '/india-admissions'
      preLoaderRoute: typeof AppIndiaAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/travel': {
      id: '/_app/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof AppTravelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/travel-destinations': {
      id: '/_app/travel-destinations'
      path: '/travel-destinations'
      fullPath: '/travel-destinations'
      preLoaderRoute: typeof AppTravelDestinationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/travel-services': {
      id: '/_app/travel-services'
      path: '/travel-services'
      fullPath: '/travel-services'
      preLoaderRoute: typeof AppTravelServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universities': {
      id: '/_app/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof AppUniversitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppHrRoute: typeof AppHrRoute
  AppIndiaAdmissionsRoute: typeof AppIndiaAdmissionsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppPortalRoute: typeof AppPortalRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTravelRoute: typeof AppTravelRoute
  AppTravelDestinationsRoute: typeof AppTravelDestinationsRoute
  AppTravelServicesRoute: typeof AppTravelServicesRoute
  AppUniversitiesRoute: typeof AppUniversitiesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppHrRoute: AppHrRoute,
  AppIndiaAdmissionsRoute: AppIndiaAdmissionsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppPortalRoute: AppPortalRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTravelRoute: AppTravelRoute,
  AppTravelDestinationsRoute: AppTravelDestinationsRoute,
  AppTravelServicesRoute: AppTravelServicesRoute,
  AppUniversitiesRoute: AppUniversitiesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DriverLoginRoute: DriverLoginRoute,
  DriverPortalRoute: DriverPortalRoute,
  LoginRoute: LoginRoute,
  TravelerLoginRoute: TravelerLoginRoute,
  TravelerPortalRoute: TravelerPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
